services:
  tracking:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317" # OpenTelemetry gRPC receiver
      - "4318:4318" # OpenTelemetry receiver
      - "14268:14268" # Jaeger receiver
      - "16686:16686" # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_rust}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_rust-password}
      POSTGRES_DB: ${POSTGRES_DB:-app_rust}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-18080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-app_rust}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-app_rust-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}



volumes:
  db: { }